const TOP_TIER_WEEK_DRAFTS = [
  {
    id: "top-tier-week-1-day-1-draft",
    title: "Top Tier",
    week: 1,
    day: 1,
    label: "Monday",
    difficulty: 1,
    theme: "Starter Signals",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Odd One Out",
        prompt: "Which option does not belong?",
        choices: ["Copper", "Silver", "Quartz", "Gold"],
        answer: "Quartz",
        explanation: "Copper, silver, and gold are metals. Quartz is a mineral.",
        editorNotes: "Friendly opener. Clean category split.",
      },
      {
        number: 2,
        tier: 1,
        type: "Sequence",
        prompt: "What comes next? 3, 6, 12, 24, ?",
        choices: ["30", "36", "48", "60"],
        answer: "48",
        explanation: "Each number doubles: 3, 6, 12, 24, 48.",
        editorNotes: "Basic sequence slot.",
      },
      {
        number: 3,
        tier: 1,
        type: "Word Fix",
        prompt: "Which word can mean \"brief\"?",
        choices: ["Short", "Rapid", "Small", "Thin"],
        answer: "Short",
        explanation:
          "Brief and short can both describe something that lasts only a little while. Rapid means fast, small means little, and thin means narrow.",
        editorNotes: "Vocabulary question with related but not exact distractors.",
      },
      {
        number: 4,
        tier: 2,
        type: "Code Shift",
        prompt: "If BIRD becomes CJSE, what does FISH become?",
        choices: ["GJTI", "EHRG", "GJSH", "FJTI"],
        answer: "GJTI",
        explanation:
          "Each letter moves forward one place in the alphabet: F-I-S-H becomes G-J-T-I.",
        editorNotes: "Teaches simple code-shift logic.",
      },
      {
        number: 5,
        tier: 2,
        type: "Number Word",
        prompt: "Which written number has the most letters?",
        choices: ["Four", "Nine", "Twelve", "Sixteen"],
        answer: "Sixteen",
        explanation:
          "Sixteen has seven letters. Twelve has six, while four and nine each have four.",
        editorNotes: "Good attention shift from number value to word length.",
      },
      {
        number: 6,
        tier: 2,
        type: "Written Forms",
        prompt: "Which option does not belong?",
        choices: ["Novel", "Poem", "Essay", "Violin"],
        answer: "Violin",
        explanation:
          "Novel, poem, and essay are written forms. Violin is a musical instrument.",
        editorNotes: "Clean Q6, though maybe a little school-like.",
      },
      {
        number: 7,
        tier: 3,
        type: "Square Pattern",
        prompt: "What comes next? 1, 4, 9, 16, ?",
        choices: ["20", "24", "25", "32"],
        answer: "25",
        explanation:
          "These are square numbers: 1 squared, 2 squared, 3 squared, 4 squared, then 5 squared.",
        editorNotes: "Classic enough to replace later.",
      },
      {
        number: 8,
        tier: 3,
        type: "Hidden Signal",
        promptHtml:
          "Read only the blue letters.<br><span class=\"signal-line\" aria-label=\"Colored letters\"><span class=\"letter-red\">T</span><span class=\"letter-blue\">C</span><span class=\"letter-green\">R</span><span class=\"letter-blue\">A</span><span class=\"letter-amber\">S</span><span class=\"letter-blue\">L</span><span class=\"letter-red\">P</span><span class=\"letter-blue\">M</span></span>",
        prompt: "Read only the blue letters: T C R A S L P M",
        choices: ["Calm", "Clam", "Claim", "Call"],
        answer: "Calm",
        explanation: "The blue letters spell C-A-L-M.",
        editorNotes: "Good visual question type. Needs richer prompt editing later.",
      },
      {
        number: 9,
        tier: 3,
        type: "Age Logic",
        prompt: "Maya is older than Leo. Leo is older than Nora. Who is youngest?",
        choices: ["Maya", "Leo", "Nora", "Cannot tell"],
        answer: "Nora",
        explanation: "The order is Maya, then Leo, then Nora. Nora is youngest.",
        editorNotes: "Clean but maybe too easy for Q9.",
      },
      {
        number: 10,
        tier: 4,
        type: "Literal Reading",
        prompt:
          "What is the unintended literal meaning of \"I turned into my driveway\"?",
        choices: [
          "I drove onto my driveway",
          "I became my driveway",
          "I repaired my driveway",
          "I missed my driveway",
        ],
        answer: "I became my driveway",
        explanation:
          "In normal speech it means entering the driveway, but \"turned into\" can also mean changed into.",
        editorNotes: "This has the Top Tier wink.",
      },
      {
        number: 11,
        tier: 4,
        type: "Cost Puzzle",
        prompt:
          "A notebook and pen cost $6 together. The notebook costs $4 more than the pen. How much is the pen?",
        choices: ["$1", "$2", "$3", "$4"],
        answer: "$1",
        explanation:
          "If the pen is $1, the notebook is $5. Together they cost $6.",
        editorNotes: "Relationship math. Good format, maybe too familiar.",
      },
      {
        number: 12,
        tier: 4,
        type: "Word Reversal",
        prompt: "Which word becomes a different word when read backward?",
        choices: ["Level", "Drawer", "Civic", "Radar"],
        answer: "Drawer",
        explanation:
          "Drawer backward is reward. Level, civic, and radar are palindromes.",
        editorNotes: "Strong final precision seed.",
      },
    ],
  },
  {
    id: "top-tier-week-1-day-2-draft",
    title: "Top Tier",
    week: 1,
    day: 2,
    label: "Tuesday",
    difficulty: 2,
    theme: "Patterns and Comparisons",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Category Break",
        prompt: "Which option does not belong?",
        choices: ["Oak", "Maple", "Pine", "Tulip"],
        answer: "Tulip",
        explanation: "Oak, maple, and pine are trees. A tulip is a flower.",
        editorNotes: "Soft start with nature categories.",
      },
      {
        number: 2,
        tier: 1,
        type: "Counting Pattern",
        prompt: "What comes next? 5, 10, 15, 20, ?",
        choices: ["22", "24", "25", "30"],
        answer: "25",
        explanation: "The numbers increase by 5 each time.",
        editorNotes: "Basic arithmetic warm-up.",
      },
      {
        number: 3,
        tier: 1,
        type: "Word Pair",
        prompt: "Which pair means nearly the same thing?",
        choices: ["Tiny / Small", "Narrow / Small", "Brief / Small", "Young / Small"],
        answer: "Tiny / Small",
        explanation: "Tiny and small are close in meaning.",
        editorNotes: "Similar-looking pair choices, but only one true synonym pair.",
      },
      {
        number: 4,
        tier: 2,
        type: "Shape Count",
        prompt: "A triangle, square, and pentagon have how many sides total?",
        choices: ["10", "11", "12", "13"],
        answer: "12",
        explanation:
          "A triangle has 3 sides, a square has 4, and a pentagon has 5. Together that is 12.",
        editorNotes: "Varies Tuesday away from another code-shift slot.",
      },
      {
        number: 5,
        tier: 2,
        type: "Month Length",
        prompt: "Which month name has the fewest letters?",
        choices: ["March", "April", "May", "June"],
        answer: "May",
        explanation: "May has three letters. The others have five.",
        editorNotes: "Attention is on the word, not the calendar.",
      },
      {
        number: 6,
        tier: 2,
        type: "Material Sort",
        prompt: "Which option does not belong?",
        choices: ["Ruby", "Emerald", "Sapphire", "Granite"],
        answer: "Granite",
        explanation:
          "Ruby, emerald, and sapphire are gemstones. Granite is a rock.",
        editorNotes: "Good visual vocabulary.",
      },
      {
        number: 7,
        tier: 3,
        type: "Growing Difference",
        prompt: "What comes next? 2, 5, 10, 17, ?",
        choices: ["24", "26", "28", "30"],
        answer: "26",
        explanation:
          "The increases are 3, 5, 7, then 9. So 17 plus 9 is 26.",
        editorNotes: "Introduces odd-number differences.",
      },
      {
        number: 8,
        tier: 3,
        type: "Order Logic",
        prompt:
          "Ava finished before Ben. Ben finished before Cole. Who finished last?",
        choices: ["Ava", "Ben", "Cole", "Cannot tell"],
        answer: "Cole",
        explanation: "The order is Ava, then Ben, then Cole.",
        editorNotes: "Clear ordering question.",
      },
      {
        number: 9,
        tier: 3,
        type: "Letter Count",
        prompt: "Which choice contains exactly two vowels?",
        choices: ["Storm", "Banana", "River", "Piano"],
        answer: "River",
        explanation:
          "River has two vowels: i and e. Storm has one vowel, while banana and piano each have three.",
        editorNotes: "Clean single-answer vowel count with one low-count and two high-count distractors.",
      },
      {
        number: 10,
        tier: 4,
        type: "Ambiguous Sentence",
        prompt: "Which sentence can accidentally sound impossible?",
        choices: [
          "I saw her duck",
          "I closed the door",
          "I held the cup",
          "I found my keys",
        ],
        answer: "I saw her duck",
        explanation:
          "Duck can be a bird or an action, so the sentence has two readings.",
        editorNotes: "Nice ambiguity seed.",
      },
      {
        number: 11,
        tier: 4,
        type: "Attention Trap",
        prompt:
          "You pass the person in second place during a race. What place are you in?",
        choices: ["First", "Second", "Third", "Fourth"],
        answer: "Second",
        explanation:
          "If you pass the person in second place, you take second place. You have not passed the person in first.",
        editorNotes: "Classic attention trap. Easier than later Top Tier questions.",
      },
      {
        number: 12,
        tier: 4,
        type: "Letter Addition",
        prompt: "Which word changes meaning when one letter is added to the front?",
        choices: ["Ring", "Chair", "Apple", "Stone"],
        answer: "Ring",
        explanation:
          "Adding w to ring makes wring, which sounds the same but means something different.",
        editorNotes: "Good homophone-style final.",
      },
    ],
  },
  {
    id: "top-tier-week-1-day-3-draft",
    title: "Top Tier",
    week: 1,
    day: 3,
    label: "Wednesday",
    difficulty: 3,
    theme: "Careful Reading",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Set Break",
        prompt: "Which option does not belong?",
        choices: ["Circle", "Square", "Triangle", "Pencil"],
        answer: "Pencil",
        explanation: "Circle, square, and triangle are shapes.",
        editorNotes: "Easy visual category.",
      },
      {
        number: 2,
        tier: 1,
        type: "Word Meaning",
        prompt: "Which word means the opposite of increase?",
        choices: ["Decrease", "Expand", "Improve", "Grow"],
        answer: "Decrease",
        explanation:
          "To decrease is to become less. Expand, improve, and grow all move closer to increasing.",
        editorNotes: "Vocabulary slot with related growth/change distractors.",
      },
      {
        number: 3,
        tier: 1,
        type: "Sound-Alike",
        prompt: "Which word sounds like a letter of the alphabet?",
        choices: ["Sea", "Tree", "Stone", "Cloud"],
        answer: "Sea",
        explanation: "Sea sounds like the letter C.",
        editorNotes: "Adds a sound-based question family.",
      },
      {
        number: 4,
        tier: 2,
        type: "Alphabet Scan",
        prompt: "Which word is alphabetically first?",
        choices: ["Marker", "Marble", "Market", "Margin"],
        answer: "Marble",
        explanation:
          "All begin with mar. The fourth letters are k, b, k, and g. B comes first.",
        editorNotes: "A bit more precise than the warm-up.",
      },
      {
        number: 5,
        tier: 2,
        type: "Animal Sort",
        prompt: "Which option does not belong?",
        choices: ["Eagle", "Robin", "Sparrow", "Dolphin"],
        answer: "Dolphin",
        explanation: "The first three are birds. A dolphin is a mammal.",
        editorNotes: "Classic but reliable.",
      },
      {
        number: 6,
        tier: 2,
        type: "Step Pattern",
        prompt: "What comes next? 3, 4, 6, 9, 13, ?",
        choices: ["16", "18", "19", "21"],
        answer: "18",
        explanation:
          "The increases are 1, 2, 3, 4, then 5. So 13 plus 5 is 18.",
        editorNotes: "Stair-step increases.",
      },
      {
        number: 7,
        tier: 3,
        type: "Missing Letter",
        prompt: "Which letter completes this pattern? A, C, E, G, ?",
        choices: ["H", "I", "J", "K"],
        answer: "I",
        explanation: "The pattern skips one letter each time: A, C, E, G, I.",
        editorNotes: "Moved later so the day ramps more gently before the skip-letter pattern.",
      },
      {
        number: 8,
        tier: 3,
        type: "Attention Trap",
        prompt: "How many times does the letter e appear in this sentence?",
        choices: ["7", "8", "9", "10"],
        answer: "10",
        explanation:
          "The sentence is: How many times does the letter e appear in this sentence? There are ten e's.",
        editorNotes: "Verify count if prompt changes.",
      },
      {
        number: 9,
        tier: 3,
        type: "Box Order",
        prompt:
          "Three boxes are labeled Red, Blue, and Green. The green box is not first. The red box is after the blue box. Which box is first?",
        choices: ["Red", "Blue", "Green", "Cannot tell"],
        answer: "Blue",
        explanation:
          "Green is not first, and red is after blue, so blue must be first.",
        editorNotes: "Good compact logic.",
      },
      {
        number: 10,
        tier: 4,
        type: "Double Meaning",
        prompt: "Which sentence has a hidden second meaning?",
        choices: [
          "The coach saw the pitcher",
          "The dog slept outside",
          "The rain stopped early",
          "The chair was wooden",
        ],
        answer: "The coach saw the pitcher",
        explanation:
          "Pitcher can mean a baseball player or a container for pouring.",
        editorNotes: "Ambiguity category.",
      },
      {
        number: 11,
        tier: 4,
        type: "Spatial Logic",
        prompt:
          "Four seats are in a row, numbered 1 to 4 from left to right. Leo is in seat 2. Nora sits next to Leo and is three seats away from Maya. Which seat is empty?",
        choices: ["Seat 1", "Seat 2", "Seat 3", "Seat 4"],
        answer: "Seat 3",
        explanation:
          "Nora must be in seat 1 so she is next to Leo and three seats away from Maya in seat 4. That leaves seat 3 empty.",
        editorNotes: "Concrete seat-placement puzzle with one open seat.",
      },
      {
        number: 12,
        tier: 4,
        type: "Word Shift",
        prompt: "Which word can become a new word by changing only its first letter?",
        choices: ["Light", "Orange", "Window", "Bottle"],
        answer: "Light",
        explanation:
          "Light can become sight, might, right, or night by changing the first letter.",
        editorNotes: "Open-ended but answer choice is strongest.",
      },
    ],
  },
  {
    id: "top-tier-week-1-day-4-draft",
    title: "Top Tier",
    week: 1,
    day: 4,
    label: "Thursday",
    difficulty: 4,
    theme: "Hidden Rules",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Outlier",
        prompt: "Which option does not belong?",
        choices: ["Hammer", "Wrench", "Screwdriver", "Blanket"],
        answer: "Blanket",
        explanation: "The first three are tools.",
        editorNotes: "Simple opener.",
      },
      {
        number: 2,
        tier: 1,
        type: "Hidden Word",
        prompt: "Which word hides a number inside it?",
        choices: ["Alone", "Planet", "Bridge", "Window"],
        answer: "Alone",
        explanation: "Alone contains one: al-ONE.",
        editorNotes: "Early signal for Thursday's hidden-rules theme.",
      },
      {
        number: 3,
        tier: 1,
        type: "Synonym",
        prompt: "Which word best means moving at high speed?",
        choices: ["Fast", "Brief", "Eager", "Sudden"],
        answer: "Fast",
        explanation:
          "Fast means moving quickly. Brief is short in time, eager means ready or excited, and sudden means unexpected.",
        editorNotes: "Language warm-up with nearby but not exact distractors.",
      },
      {
        number: 4,
        tier: 2,
        type: "Rule Breaker",
        prompt: "Which choice breaks the rule: each word starts and ends with the same letter?",
        choices: ["Radar", "Level", "Civic", "Apple"],
        answer: "Apple",
        explanation:
          "Radar, level, and civic start and end with the same letter. Apple starts with a and ends with e.",
        editorNotes: "Moved earlier because this is a clean but lighter rule-check question.",
      },
      {
        number: 5,
        tier: 2,
        type: "Alphabet Rule",
        prompt: "Which choice has letters in alphabetical order?",
        choices: ["Almost", "Ghost", "Adept", "Began"],
        answer: "Adept",
        explanation: "A, d, e, p, t appear in alphabetical order.",
        editorNotes: "Nice letter-order attention.",
      },
      {
        number: 6,
        tier: 2,
        type: "Planet Check",
        prompt: "Which option does not belong?",
        choices: ["Mercury", "Venus", "Mars", "Pluto"],
        answer: "Pluto",
        explanation:
          "Mercury, Venus, and Mars are planets. Pluto is classified as a dwarf planet.",
        editorNotes: "May invite debate, but useful as a trap.",
      },
      {
        number: 7,
        tier: 3,
        type: "Letter Shift",
        prompt: "If COLD becomes EQNF, what does WARM become?",
        choices: ["YCTO", "XBSN", "VZQL", "YBSO"],
        answer: "YCTO",
        explanation: "Each letter moves forward two places.",
        editorNotes: "Moved later to give Tier 3 a stronger pattern challenge.",
      },
      {
        number: 8,
        tier: 3,
        type: "Hidden Rule",
        prompt: "Which number belongs with this set? 14, 23, 32, 41",
        choices: ["50", "52", "61", "70"],
        answer: "50",
        explanation:
          "In each number, the two digits add to 5. In 50, 5 plus 0 also equals 5.",
        editorNotes: "Clear hidden rule with a mild trap.",
      },
      {
        number: 9,
        tier: 3,
        type: "Door Logic",
        prompt:
          "No silver keys open the blue door. This key opens the blue door. What must be true?",
        choices: [
          "The key is silver",
          "The key is not silver",
          "The key is blue",
          "The door is silver",
        ],
        answer: "The key is not silver",
        explanation:
          "If no silver keys open the blue door, a key that opens it cannot be silver.",
        editorNotes: "Good deductive logic.",
      },
      {
        number: 10,
        tier: 4,
        type: "Ambiguous Phrase",
        prompt: "Which phrase can mean two different things?",
        choices: ["Flying planes", "Broken pencil", "Cold soup", "Red apple"],
        answer: "Flying planes",
        explanation:
          "It can mean planes that are flying or the act of flying planes.",
        editorNotes: "Strong language trap.",
      },
      {
        number: 11,
        tier: 4,
        type: "Rule Logic",
        prompt:
          "A code accepts words with exactly one doubled letter. Which word would the code accept?",
        choices: ["Apple", "Balloon", "Coffee", "River"],
        answer: "Apple",
        explanation:
          "Apple has exactly one doubled letter: pp. Balloon and coffee each have two doubled pairs, and river has none.",
        editorNotes: "Harder rule-checking question.",
      },
      {
        number: 12,
        tier: 4,
        type: "Compound Bridge",
        prompt:
          "Which word can follow both \"book\" and \"water\" to make common compound words?",
        choices: ["Mark", "Fall", "Light", "Stone"],
        answer: "Mark",
        explanation: "Bookmark and watermark are both common words.",
        editorNotes: "Elegant compound-word final.",
      },
    ],
  },
  {
    id: "top-tier-week-1-day-5-draft",
    title: "Top Tier",
    week: 1,
    day: 5,
    label: "Friday",
    difficulty: 5,
    theme: "Traps and Turns",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Odd One Out",
        prompt: "Which option does not belong?",
        choices: ["Bass", "Drum", "Flute", "Canvas"],
        answer: "Canvas",
        explanation: "Bass, drum, and flute are musical instruments.",
        editorNotes: "Easy but not too plain.",
      },
      {
        number: 2,
        tier: 1,
        type: "Even Step",
        prompt: "What comes next? 4, 8, 12, 16, ?",
        choices: ["18", "20", "22", "24"],
        answer: "20",
        explanation: "The numbers increase by 4.",
        editorNotes: "Warm-up sequence.",
      },
      {
        number: 3,
        tier: 1,
        type: "Synonym",
        prompt: "Which word best describes someone calm under pressure?",
        choices: ["Steady", "Quiet", "Still", "Careful"],
        answer: "Steady",
        explanation:
          "Steady can describe someone calm and controlled under pressure. Quiet, still, and careful are related qualities but do not capture the pressure part as well.",
        editorNotes: "Good emotional vocabulary with plausible distractors.",
      },
      {
        number: 4,
        tier: 2,
        type: "Word Ladder",
        prompt: "Change one letter in cold to make something valuable.",
        choices: ["Gold", "Bold", "Cord", "Fold"],
        answer: "Gold",
        explanation: "Changing c to g turns cold into gold.",
        editorNotes: "Friday gets a word-transformation slot instead of code shift.",
      },
      {
        number: 5,
        tier: 2,
        type: "Repeat Check",
        prompt: "Which word contains no repeated letters?",
        choices: ["Letter", "Mirror", "Planet", "Bubble"],
        answer: "Planet",
        explanation: "Planet uses each letter once.",
        editorNotes: "Good scanning question.",
      },
      {
        number: 6,
        tier: 2,
        type: "Substance Sort",
        prompt: "Which option does not belong?",
        choices: ["Ice", "Steam", "Water", "Smoke"],
        answer: "Smoke",
        explanation: "Ice, steam, and water are forms of water. Smoke is not.",
        editorNotes: "Clean science category.",
      },
      {
        number: 7,
        tier: 3,
        type: "Add-One Pattern",
        prompt: "What comes next? 2, 3, 5, 8, 12, ?",
        choices: ["15", "16", "17", "18"],
        answer: "17",
        explanation:
          "The increases are 1, 2, 3, 4, then 5. So 12 plus 5 is 17.",
        editorNotes: "Good Friday mid-game.",
      },
      {
        number: 8,
        tier: 3,
        type: "Hidden Signal",
        prompt: "Which word hides an animal inside it?",
        choices: ["Scattered", "Column", "Window", "Planet"],
        answer: "Scattered",
        explanation:
          "Scattered contains cat in consecutive letters: s-CAT-tered.",
        editorNotes: "Cleaner hidden-word question with one animal hidden in consecutive letters.",
      },
      {
        number: 9,
        tier: 3,
        type: "Color Logic",
        prompt:
          "Every marble in the bag is blue or green. None are green. What color are they?",
        choices: ["Blue", "Green", "Red", "Cannot tell"],
        answer: "Blue",
        explanation:
          "If each marble is blue or green, and none are green, they must be blue.",
        editorNotes: "Good clean logic.",
      },
      {
        number: 10,
        tier: 4,
        type: "Comma Trap",
        prompt: "Which sentence changes meaning if you pause after the first word?",
        choices: ["Let's eat, Grandma", "I read books", "The sun rose", "He closed it"],
        answer: "Let's eat, Grandma",
        explanation:
          "Without the pause, it can sound like Grandma is being eaten. With it, Grandma is being addressed.",
        editorNotes: "Punctuation-based trap.",
      },
      {
        number: 11,
        tier: 4,
        type: "Probability Check",
        prompt:
          "A bag has 1 blue tile and 3 red tiles. You draw one tile. What is the probability of drawing the blue tile?",
        choices: ["66%", "33%", "75%", "25%"],
        answer: "25%",
        explanation:
          "There are 4 tiles total, and 1 of them is blue. That makes the chance of drawing blue 1 out of 4, or 25%.",
        editorNotes: "Percentage-based probability check with plausible distractors.",
      },
      {
        number: 12,
        tier: 4,
        type: "Prefix Trap",
        prompt: "Which word does not become its opposite when a two-letter prefix is added?",
        choices: ["Possible", "Known", "Legal", "Flammable"],
        answer: "Flammable",
        explanation:
          "Impossible, unknown, and illegal are opposites. Inflammable means flammable, not the opposite.",
        editorNotes: "Harder prefix trap for the final question.",
      },
    ],
  },
  {
    id: "top-tier-week-1-day-6-draft",
    title: "Top Tier",
    week: 1,
    day: 6,
    label: "Saturday",
    difficulty: 6,
    theme: "Weekend Stretch",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Position Sort",
        prompt: "Which option does not belong?",
        choices: ["North", "South", "Center", "East"],
        answer: "Center",
        explanation: "North, south, and east are compass directions.",
        editorNotes: "Good Saturday opener.",
      },
      {
        number: 2,
        tier: 1,
        type: "Weekend Warm-Up",
        prompt: "What comes next? 6, 12, 18, 24, ?",
        choices: ["28", "30", "32", "36"],
        answer: "30",
        explanation: "The numbers increase by 6.",
        editorNotes: "Warm but slightly bigger numbers.",
      },
      {
        number: 3,
        tier: 1,
        type: "Word Meaning",
        prompt: "Which word means almost the same as exact?",
        choices: ["Precise", "Careful", "Detailed", "Close"],
        answer: "Precise",
        explanation:
          "Exact and precise both mean very accurate. Careful, detailed, and close can help accuracy, but they do not mean exact.",
        editorNotes: "Good tone for harder day with stronger vocabulary distractors.",
      },
      {
        number: 4,
        tier: 2,
        type: "Anagram",
        prompt: "Which choice can be made from the letters in LISTEN?",
        choices: ["Silent", "Inlets", "Tinsel", "All of these"],
        answer: "All of these",
        explanation:
          "Silent, inlets, and tinsel all use the same six letters as listen.",
        editorNotes: "Adds an anagram family for the weekend.",
      },
      {
        number: 5,
        tier: 2,
        type: "Alphabet Order",
        prompt: "Which choice is not in alphabetical order?",
        choices: ["Almost", "Begin", "Ghost", "Zebra"],
        answer: "Zebra",
        explanation:
          "Almost, begin, and ghost move forward alphabetically. Zebra starts with z and then moves backward to e.",
        editorNotes: "Fixed answer and explanation.",
      },
      {
        number: 6,
        tier: 2,
        type: "Three Clue",
        prompt: "Which option does not belong?",
        choices: ["Triangle", "Tripod", "Trio", "Trickle"],
        answer: "Trickle",
        explanation:
          "Triangle, tripod, and trio all connect to three. Trickle does not.",
        editorNotes: "Nice prefix/meaning category.",
      },
      {
        number: 7,
        tier: 3,
        type: "Fibonacci Pattern",
        prompt: "What comes next? 1, 1, 2, 3, 5, 8, ?",
        choices: ["11", "12", "13", "15"],
        answer: "13",
        explanation: "Each number is the sum of the two before it.",
        editorNotes: "Fibonacci seed.",
      },
      {
        number: 8,
        tier: 3,
        type: "Attention Trap",
        prompt: "Which choice has the same number of letters as its number?",
        choices: ["One", "Two", "Three", "Four"],
        answer: "Four",
        explanation: "Four has four letters.",
        editorNotes: "Fun clean attention question.",
      },
      {
        number: 9,
        tier: 3,
        type: "Formal Logic",
        prompt:
          "If all glips are nords, and no nords are blins, can a glip be a blin?",
        choices: ["Yes", "No", "Only sometimes", "Cannot tell"],
        answer: "No",
        explanation:
          "Every glip is a nord, and no nord is a blin, so no glip can be a blin.",
        editorNotes: "Abstract logic for harder day.",
      },
      {
        number: 10,
        tier: 4,
        type: "Grammar Trap",
        prompt:
          "Which sentence can mean either ownership or action?",
        choices: [
          "The man's painting hangs on the wall",
          "The glass is empty",
          "The road is narrow",
          "The bell is loud",
        ],
        answer: "The man's painting hangs on the wall",
        explanation:
          "It can mean a painting owned by the man, or a painting made by the man, hanging on the wall.",
        editorNotes: "Strong ambiguity.",
      },
      {
        number: 11,
        tier: 4,
        type: "Grid Logic",
        prompt:
          "A 2 by 3 rectangle is made of unit squares. How many unit squares does it contain?",
        choices: ["5", "6", "8", "9"],
        answer: "6",
        explanation: "Two rows of three squares make 2 x 3, or 6 unit squares.",
        editorNotes: "Spatial numeric reasoning instead of another price trap.",
      },
      {
        number: 12,
        tier: 4,
        type: "Compound Pair",
        prompt:
          "Which word can follow both \"over\" and \"under\" to make common roadway words?",
        choices: ["Pass", "Path", "Light", "Stone"],
        answer: "Pass",
        explanation: "Overpass and underpass are both common roadway words.",
        editorNotes: "Roadway-specific compound-word final to avoid overline and underline.",
      },
    ],
  },
  {
    id: "top-tier-week-1-day-7-draft",
    title: "Top Tier",
    week: 1,
    day: 7,
    label: "Sunday",
    difficulty: 7,
    theme: "Top Tier Trial",
    tagline: "12 questions. 4 tiers. 30 seconds each.",
    catchphrase: "Can you reach the Top Tier?",
    status: "draft",
    finalizedAt: "",
    editor: {
      name: "",
      newsOrganization: "",
      notes: "",
    },
    questions: [
      {
        number: 1,
        tier: 1,
        type: "Reflection Set",
        prompt: "Which option does not belong?",
        choices: ["Echo", "Shadow", "Reflection", "Candle"],
        answer: "Candle",
        explanation:
          "Echo, shadow, and reflection are effects or copies. A candle is an object.",
        editorNotes: "Harder opening category.",
      },
      {
        number: 2,
        tier: 1,
        type: "Sevens Pattern",
        prompt: "What comes next? 7, 14, 21, 28, ?",
        choices: ["32", "35", "36", "42"],
        answer: "35",
        explanation: "The numbers increase by 7.",
        editorNotes: "Still accessible.",
      },
      {
        number: 3,
        tier: 1,
        type: "Word Meaning",
        prompt: "Which word means to look briefly?",
        choices: ["Glance", "Study", "Peruse", "Analyze"],
        answer: "Glance",
        explanation:
          "To glance is to look quickly or briefly. Study, peruse, and analyze all suggest a more careful look.",
        editorNotes: "Vocabulary warm-up with close but wrong reading-related distractors.",
      },
      {
        number: 4,
        tier: 2,
        type: "Hidden Signal",
        prompt: "Read the even-position letters: S T A O R N E E",
        choices: ["Tone", "Stone", "Torn", "Stare"],
        answer: "Tone",
        explanation:
          "The even-position letters are T-O-N-E.",
        editorNotes: "Harder hidden-signal prompt for Sunday.",
      },
      {
        number: 5,
        tier: 2,
        type: "Reverse Order",
        prompt: "Which word has its letters in reverse alphabetical order?",
        choices: ["Told", "Spoon", "Wolf", "Tone"],
        answer: "Told",
        explanation: "T-o-l-d moves backward alphabetically at each step.",
        editorNotes: "Nice precise reading.",
      },
      {
        number: 6,
        tier: 2,
        type: "Prefix Trap",
        prompt: "Which option does not belong?",
        choices: ["Prefix", "Preheat", "Preview", "Prevent"],
        answer: "Prevent",
        explanation:
          "Prefix, preheat, and preview use pre to mean before. Prevent does not mean before-vent.",
        editorNotes: "Good language trap.",
      },
      {
        number: 7,
        tier: 3,
        type: "Difference Ladder",
        prompt: "What comes next? 2, 4, 8, 14, 22, ?",
        choices: ["30", "32", "34", "36"],
        answer: "32",
        explanation:
          "The increases are 2, 4, 6, 8, then 10. So 22 plus 10 is 32.",
        editorNotes: "Strong Q7.",
      },
      {
        number: 8,
        tier: 3,
        type: "Hidden Sound",
        prompt: "Which choice does not hide a sound-related word inside it?",
        choices: ["Stone", "Cloud", "Bring", "Brave"],
        answer: "Brave",
        explanation:
          "Stone hides tone, cloud hides loud, and bring hides ring. Brave does not hide a sound-related word.",
        editorNotes: "Hidden-sound clue with one clean exception.",
      },
      {
        number: 9,
        tier: 3,
        type: "Must-Be-True",
        prompt:
          "Every zarn is a veek. No veeks are loms. What cannot be true?",
        choices: [
          "A zarn is a veek",
          "A veek is not a zarn",
          "A zarn is a lom",
          "A lom is not a veek",
        ],
        answer: "A zarn is a lom",
        explanation:
          "Every zarn is a veek, and no veeks are loms. So a zarn cannot be a lom.",
        editorNotes: "Stronger counter-logic question that requires inference.",
      },
      {
        number: 10,
        tier: 4,
        type: "Role Ambiguity",
        prompt: "Which phrase can describe both a person and a job?",
        choices: ["Fast runner", "Heavy sleeper", "Light sleeper", "Sound engineer"],
        answer: "Sound engineer",
        explanation:
          "It can mean an engineer who works with sound, or a reliable engineer.",
        editorNotes: "May be subtle; good Top Tier feel.",
      },
      {
        number: 11,
        tier: 4,
        type: "Constraint Logic",
        prompt:
          "A code must contain exactly one vowel, one even digit, and one compass direction. Which code works?",
        choices: ["A-4-North", "B-4-North", "A-5-North", "A-4-Table"],
        answer: "B-4-North",
        explanation:
          "B-4-North has exactly one vowel, the o in North. It also has the even digit 4 and the compass direction North.",
        editorNotes: "Top Tier-style checklist logic with A-4-North as the vowel-count trap.",
      },
      {
        number: 12,
        tier: 4,
        type: "Part of Speech Shift",
        prompt:
          "Which word changes from a noun to a verb when one silent letter is added to the front?",
        choices: ["Rite", "Road", "Rain", "Roof"],
        answer: "Rite",
        explanation:
          "Adding w makes write, a verb that sounds like rite but has a different meaning.",
        editorNotes: "Harder homophone-style final without repeating Tuesday's answer.",
      },
    ],
  },
];

const TOP_TIER_DRAFT_GAME = TOP_TIER_WEEK_DRAFTS[0];
